# Required
image:
host:

# Optional
clusterIssuer: letsencrypt
containerPort: 80
wwwRedirect: false
changeCause: null
replicas: 1
dockerRegistry: null
dockerRegistryAuth: null
CI_PROJECT_PATH_SLUG:
CI_ENVIRONMENT_SLUG:
