apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}{{ .Release.Name }}
  labels:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
data:
  prometheus.yml: |
{{ required ".Values.prometheus_yml is required" .Values.prometheus_yml | indent 4 }}
