apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.namePrefix }}{{ .Release.Name }}
  labels:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
spec:
  serviceName: {{ .Values.namePrefix }}{{ .Release.Name }}
  selector:
    matchLabels:
      release: {{ .Values.namePrefix }}{{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/configmap.yml") . | sha256sum}}
      labels:
        release: {{ .Values.namePrefix }}{{ .Release.Name }}
    spec:
      containers:
      - name: main
        image: prom/prometheus
        ports:
          - name: prom
            containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: prom
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          subPath: prometheus.yml
          mountPath: /etc/prometheus/prometheus.yml
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ .Values.namePrefix }}{{ .Release.Name }}
