apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}{{ .Release.Name }}
  labels:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: prom
      name: prom
  selector:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
