apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
data:
  grafana.ini: |
{{ required ".Values.grafana_ini is required" .Values.grafana_ini | indent 4 }}
