apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.proxyBodySize }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
        {{ if .Values.hostReadOnly }}
        - {{ .Values.hostReadOnly }}
        {{ end }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
    {{ if .Values.hostReadOnly }}
    - host: {{ .Values.hostReadOnly }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-readonly
                port:
                  name: http
    {{ end }}
