apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  runner-registration-token: {{ required ".Values.runnerRegistrationToken is required" .Values.runnerRegistrationToken }}
