apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}{{ .Release.Name }}
  labels:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
data:
  config.yml: |
{{ required ".Values.config_yml is required" .Values.config_yml | indent 4 }}
