apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}{{ .Release.Name }}
  labels:
    release: {{ .Values.namePrefix }}{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      release: {{ .Values.namePrefix }}{{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/configmap.yml") . | sha256sum}}
      labels:
        release: {{ .Values.namePrefix }}{{ .Release.Name }}
    spec:
      containers:
      - name: main
        image: {{ .Values.image }}
        args:
          - /bin/sh
          - -c
          - slu metrics-generator server -c /config.yml
        ports:
          - name: http
            containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
        - name: config
          subPath: config.yml
          mountPath: /config.yml
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ .Values.namePrefix }}{{ .Release.Name }}
