{{- if and (.Values.dockerRegistry) (.Values.dockerRegistryAuth) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Release.Name }}-docker
  labels:
    release: {{ .Release.Name }}
stringData:
  .dockerconfigjson: '{"auths": {"{{ .Values.dockerRegistry }}": {"auth": "{{ .Values.dockerRegistryAuth }}"}}}'
{{ end }}
