{{ if .Values.basicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ .Values.basicAuth | b64enc }}
{{ end }}
