{{ if and (.Values.basicAuth.username) (.Values.basicAuth.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ (htpasswd .Values.basicAuth.username .Values.basicAuth.password) | b64enc }}
{{ end }}
